package TestNG.Thinking_in_Java.generics.watercolors;

/**@author DreamYao
 * Created by DreamYao on 2016/10/17.
 * P367 颜色枚举
 */
public enum  Watercolors {
    ZINC,LEMON,YELLOW,MEDIUM_YELLOW,DEEP_YELLOW,ORANGE,
    BRILLIANT_RED,CRIMSON,MAGENTA,ROSE_MADDER,VIOLET,
    CERULEAN_BLUE_HUE,PHTHALO_BLUE,ULTRAMARINE,
    COBALT_BLUE_HUE,PERMANENT_GREEN,VIRIDIAN_HUE,
    SAP_GREEN,YELLOW_OCHRE,BURNT_SINENNA,RAW_UMBER,
    BURNT_UMBER,PAYNES_GRAY,IVORY_BLACK
}
